server:
  port: 8090

spring:
  application:
    name: yiling-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/yiling?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: yiling
    password: yiling123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: none

yiling:
  jwt:
    secret: "yiling-manager-jwt-secret-key-please-change-in-production-2026"
    expire-seconds: 43200
